-- =====================================================
-- Analytics Schema Tables - Dimensional Model
-- Description: Data warehouse dimensional tables for analytics
-- Version: 1.0
-- Date: 2025-07-19
-- =====================================================

USE SCHEMA RETAILWORKS_DB.ANALYTICS_SCHEMA;

-- Date Dimension Table
CREATE OR REPLACE TABLE DATE_DIM (
    DATE_KEY NUMBER(8,0) PRIMARY KEY,
    DATE_ACTUAL DATE NOT NULL UNIQUE,
    DAY_OF_WEEK NUMBER(1,0) NOT NULL,
    DAY_OF_WEEK_NAME VARCHAR(10) NOT NULL,
    DAY_OF_MONTH NUMBER(2,0) NOT NULL,
    DAY_OF_YEAR NUMBER(3,0) NOT NULL,
    WEEK_OF_YEAR NUMBER(2,0) NOT NULL,
    MONTH_NUMBER NUMBER(2,0) NOT NULL,
    MONTH_NAME VARCHAR(10) NOT NULL,
    MONTH_ABBR VARCHAR(3) NOT NULL,
    QUARTER_NUMBER NUMBER(1,0) NOT NULL,
    QUARTER_NAME VARCHAR(2) NOT NULL,
    YEAR_NUMBER NUMBER(4,0) NOT NULL,
    IS_WEEKEND BOOLEAN NOT NULL,
    IS_HOLIDAY BOOLEAN DEFAULT FALSE,
    HOLIDAY_NAME VARCHAR(50),
    FISCAL_YEAR NUMBER(4,0),
    FISCAL_QUARTER NUMBER(1,0),
    FISCAL_MONTH NUMBER(2,0),
    SEASON VARCHAR(10),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Customer Dimension Table
CREATE OR REPLACE TABLE CUSTOMER_DIM (
    CUSTOMER_KEY NUMBER(10,0) AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID NUMBER(10,0) NOT NULL,
    CUSTOMER_NUMBER VARCHAR(20) NOT NULL,
    CUSTOMER_NAME VARCHAR(200) NOT NULL,
    CUSTOMER_TYPE VARCHAR(20),
    COMPANY_NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    BIRTH_DATE DATE,
    GENDER VARCHAR(10),
    AGE_GROUP VARCHAR(20),
    MARITAL_STATUS VARCHAR(20),
    EDUCATION VARCHAR(50),
    OCCUPATION VARCHAR(100),
    ANNUAL_INCOME DECIMAL(15,2),
    INCOME_CATEGORY VARCHAR(20),
    SEGMENT_NAME VARCHAR(50),
    BILLING_CITY VARCHAR(50),
    BILLING_STATE VARCHAR(50),
    BILLING_COUNTRY VARCHAR(30),
    SHIPPING_CITY VARCHAR(50),
    SHIPPING_STATE VARCHAR(50),
    SHIPPING_COUNTRY VARCHAR(30),
    REGISTRATION_DATE DATE,
    STATUS VARCHAR(20),
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    VERSION NUMBER(10,0) DEFAULT 1,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE(CUSTOMER_ID, VERSION)
);

-- Product Dimension Table
CREATE OR REPLACE TABLE PRODUCT_DIM (
    PRODUCT_KEY NUMBER(10,0) AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID NUMBER(10,0) NOT NULL,
    PRODUCT_NUMBER VARCHAR(25) NOT NULL,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    CATEGORY_NAME VARCHAR(50),
    CATEGORY_HIERARCHY VARCHAR(200),
    SUPPLIER_NAME VARCHAR(100),
    SUPPLIER_COUNTRY VARCHAR(30),
    COLOR VARCHAR(15),
    SIZE VARCHAR(10),
    WEIGHT DECIMAL(8,2),
    UNIT_PRICE DECIMAL(10,2),
    COST DECIMAL(10,2),
    LIST_PRICE DECIMAL(10,2),
    PRODUCT_LINE VARCHAR(20),
    CLASS VARCHAR(10),
    STYLE VARCHAR(10),
    DISCONTINUED BOOLEAN,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    VERSION NUMBER(10,0) DEFAULT 1,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE(PRODUCT_ID, VERSION)
);

-- Sales Rep Dimension Table
CREATE OR REPLACE TABLE SALES_REP_DIM (
    SALES_REP_KEY NUMBER(10,0) AUTOINCREMENT PRIMARY KEY,
    SALES_REP_ID NUMBER(10,0) NOT NULL,
    EMPLOYEE_ID NUMBER(10,0),
    SALES_REP_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    TERRITORY_NAME VARCHAR(50),
    TERRITORY_CODE VARCHAR(10),
    REGION VARCHAR(30),
    COUNTRY VARCHAR(30),
    HIRE_DATE DATE,
    COMMISSION_RATE DECIMAL(5,4),
    STATUS VARCHAR(20),
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    VERSION NUMBER(10,0) DEFAULT 1,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE(SALES_REP_ID, VERSION)
);

-- Sales Fact Table
CREATE OR REPLACE TABLE SALES_FACT (
    SALES_FACT_ID NUMBER(15,0) AUTOINCREMENT PRIMARY KEY,
    ORDER_ID NUMBER(10,0) NOT NULL,
    ORDER_ITEM_ID NUMBER(10,0) NOT NULL,
    ORDER_DATE_KEY NUMBER(8,0) NOT NULL,
    SHIPPED_DATE_KEY NUMBER(8,0),
    CUSTOMER_KEY NUMBER(10,0) NOT NULL,
    PRODUCT_KEY NUMBER(10,0) NOT NULL,
    SALES_REP_KEY NUMBER(10,0),
    QUANTITY NUMBER(10,0) NOT NULL,
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    DISCOUNT DECIMAL(5,4) DEFAULT 0.00,
    LINE_TOTAL DECIMAL(12,2) NOT NULL,
    COST DECIMAL(10,2),
    PROFIT DECIMAL(12,2),
    FREIGHT DECIMAL(10,2),
    TAX_AMOUNT DECIMAL(10,2),
    ORDER_STATUS VARCHAR(20),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (ORDER_DATE_KEY) REFERENCES DATE_DIM(DATE_KEY),
    FOREIGN KEY (SHIPPED_DATE_KEY) REFERENCES DATE_DIM(DATE_KEY),
    FOREIGN KEY (CUSTOMER_KEY) REFERENCES CUSTOMER_DIM(CUSTOMER_KEY),
    FOREIGN KEY (PRODUCT_KEY) REFERENCES PRODUCT_DIM(PRODUCT_KEY),
    FOREIGN KEY (SALES_REP_KEY) REFERENCES SALES_REP_DIM(SALES_REP_KEY)
);

-- Customer Lifetime Value Fact Table
CREATE OR REPLACE TABLE CUSTOMER_LTV_FACT (
    LTV_FACT_ID NUMBER(15,0) AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_KEY NUMBER(10,0) NOT NULL,
    CALCULATION_DATE_KEY NUMBER(8,0) NOT NULL,
    TOTAL_ORDERS NUMBER(10,0) DEFAULT 0,
    TOTAL_SPENT DECIMAL(15,2) DEFAULT 0.00,
    AVERAGE_ORDER_VALUE DECIMAL(12,2) DEFAULT 0.00,
    DAYS_SINCE_FIRST_ORDER NUMBER(10,0),
    DAYS_SINCE_LAST_ORDER NUMBER(10,0),
    ORDER_FREQUENCY DECIMAL(8,4),
    PREDICTED_LTV DECIMAL(15,2),
    CUSTOMER_SCORE DECIMAL(5,2),
    CHURN_PROBABILITY DECIMAL(5,4),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (CUSTOMER_KEY) REFERENCES CUSTOMER_DIM(CUSTOMER_KEY),
    FOREIGN KEY (CALCULATION_DATE_KEY) REFERENCES DATE_DIM(DATE_KEY)
);

-- Product Performance Fact Table
CREATE OR REPLACE TABLE PRODUCT_PERFORMANCE_FACT (
    PRODUCT_PERF_ID NUMBER(15,0) AUTOINCREMENT PRIMARY KEY,
    PRODUCT_KEY NUMBER(10,0) NOT NULL,
    DATE_KEY NUMBER(8,0) NOT NULL,
    UNITS_SOLD NUMBER(10,0) DEFAULT 0,
    REVENUE DECIMAL(15,2) DEFAULT 0.00,
    COST DECIMAL(15,2) DEFAULT 0.00,
    PROFIT DECIMAL(15,2) DEFAULT 0.00,
    RETURNS NUMBER(10,0) DEFAULT 0,
    RETURN_RATE DECIMAL(5,4) DEFAULT 0.00,
    INVENTORY_TURNS DECIMAL(8,4),
    MARGIN_PERCENT DECIMAL(5,4),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (PRODUCT_KEY) REFERENCES PRODUCT_DIM(PRODUCT_KEY),
    FOREIGN KEY (DATE_KEY) REFERENCES DATE_DIM(DATE_KEY)
);

-- Create indexes for performance
CREATE INDEX IDX_SALES_FACT_ORDER_DATE ON SALES_FACT(ORDER_DATE_KEY);
CREATE INDEX IDX_SALES_FACT_CUSTOMER ON SALES_FACT(CUSTOMER_KEY);
CREATE INDEX IDX_SALES_FACT_PRODUCT ON SALES_FACT(PRODUCT_KEY);
CREATE INDEX IDX_SALES_FACT_SALES_REP ON SALES_FACT(SALES_REP_KEY);
CREATE INDEX IDX_CUSTOMER_LTV_CUSTOMER ON CUSTOMER_LTV_FACT(CUSTOMER_KEY);
CREATE INDEX IDX_CUSTOMER_LTV_DATE ON CUSTOMER_LTV_FACT(CALCULATION_DATE_KEY);
CREATE INDEX IDX_PRODUCT_PERF_PRODUCT ON PRODUCT_PERFORMANCE_FACT(PRODUCT_KEY);
CREATE INDEX IDX_PRODUCT_PERF_DATE ON PRODUCT_PERFORMANCE_FACT(DATE_KEY);
CREATE INDEX IDX_DATE_DIM_ACTUAL ON DATE_DIM(DATE_ACTUAL);