-- =====================================================
-- Customers Schema Tables
-- Description: Tables for customer information and segmentation
-- Version: 1.0
-- Date: 2025-07-19
-- =====================================================

USE SCHEMA RETAILWORKS_DB.CUSTOMERS_SCHEMA;

-- Customer Segments Table
CREATE OR REPLACE TABLE CUSTOMER_SEGMENTS (
    SEGMENT_ID NUMBER(10,0) AUTOINCREMENT PRIMARY KEY,
    SEGMENT_NAME VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPTION TEXT,
    MIN_ANNUAL_REVENUE DECIMAL(15,2),
    MAX_ANNUAL_REVENUE DECIMAL(15,2),
    DISCOUNT_RATE DECIMAL(5,4) DEFAULT 0.00,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Addresses Table
CREATE OR REPLACE TABLE ADDRESSES (
    ADDRESS_ID NUMBER(10,0) AUTOINCREMENT PRIMARY KEY,
    ADDRESS_LINE_1 VARCHAR(200) NOT NULL,
    ADDRESS_LINE_2 VARCHAR(200),
    CITY VARCHAR(50) NOT NULL,
    STATE_PROVINCE VARCHAR(50),
    POSTAL_CODE VARCHAR(20),
    COUNTRY VARCHAR(30) NOT NULL,
    ADDRESS_TYPE VARCHAR(20) DEFAULT 'BILLING',
    LATITUDE DECIMAL(10,8),
    LONGITUDE DECIMAL(11,8),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Customers Table
CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER(10,0) AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_NUMBER VARCHAR(20) NOT NULL UNIQUE,
    CUSTOMER_TYPE VARCHAR(20) DEFAULT 'INDIVIDUAL',
    COMPANY_NAME VARCHAR(100),
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    TITLE VARCHAR(50),
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20),
    MOBILE VARCHAR(20),
    BIRTH_DATE DATE,
    GENDER VARCHAR(10),
    MARITAL_STATUS VARCHAR(20),
    EDUCATION VARCHAR(50),
    OCCUPATION VARCHAR(100),
    ANNUAL_INCOME DECIMAL(15,2),
    SEGMENT_ID NUMBER(10,0),
    BILLING_ADDRESS_ID NUMBER(10,0),
    SHIPPING_ADDRESS_ID NUMBER(10,0),
    REGISTRATION_DATE DATE NOT NULL,
    LAST_ORDER_DATE DATE,
    TOTAL_ORDERS NUMBER(10,0) DEFAULT 0,
    TOTAL_SPENT DECIMAL(15,2) DEFAULT 0.00,
    CREDIT_LIMIT DECIMAL(15,2),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    PREFERRED_LANGUAGE VARCHAR(10) DEFAULT 'EN',
    MARKETING_OPT_IN BOOLEAN DEFAULT TRUE,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (SEGMENT_ID) REFERENCES CUSTOMER_SEGMENTS(SEGMENT_ID),
    FOREIGN KEY (BILLING_ADDRESS_ID) REFERENCES ADDRESSES(ADDRESS_ID),
    FOREIGN KEY (SHIPPING_ADDRESS_ID) REFERENCES ADDRESSES(ADDRESS_ID)
);

-- Customer Address Mapping Table (for multiple addresses)
CREATE OR REPLACE TABLE CUSTOMER_ADDRESSES (
    CUSTOMER_ADDRESS_ID NUMBER(10,0) AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID NUMBER(10,0) NOT NULL,
    ADDRESS_ID NUMBER(10,0) NOT NULL,
    ADDRESS_TYPE VARCHAR(20) NOT NULL,
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESSES(ADDRESS_ID),
    UNIQUE(CUSTOMER_ID, ADDRESS_ID, ADDRESS_TYPE)
);

-- Create indexes for performance
CREATE INDEX IDX_CUSTOMERS_EMAIL ON CUSTOMERS(EMAIL);
CREATE INDEX IDX_CUSTOMERS_SEGMENT_ID ON CUSTOMERS(SEGMENT_ID);
CREATE INDEX IDX_CUSTOMERS_STATUS ON CUSTOMERS(STATUS);
CREATE INDEX IDX_CUSTOMERS_REGISTRATION_DATE ON CUSTOMERS(REGISTRATION_DATE);
CREATE INDEX IDX_CUSTOMER_ADDRESSES_CUSTOMER_ID ON CUSTOMER_ADDRESSES(CUSTOMER_ID);
CREATE INDEX IDX_ADDRESSES_CITY_COUNTRY ON ADDRESSES(CITY, COUNTRY);