-- =====================================================
-- HR Schema Tables
-- Description: Tables for human resources management
-- Version: 1.0
-- Date: 2025-07-19
-- =====================================================

USE SCHEMA RETAILWORKS_DB.HR_SCHEMA;

-- Departments Table
CREATE TABLE IF NOT EXISTS DEPARTMENTS (
    DEPARTMENT_ID NUMBER(10,0) AUTOINCREMENT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(50) NOT NULL UNIQUE,
    DEPARTMENT_CODE VARCHAR(10) NOT NULL UNIQUE,
    DESCRIPTION TEXT,
    MANAGER_ID NUMBER(10,0),
    BUDGET DECIMAL(15,2),
    LOCATION VARCHAR(100),
    PHONE VARCHAR(20),
    EMAIL VARCHAR(100),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Positions Table
CREATE TABLE IF NOT EXISTS POSITIONS (
    POSITION_ID NUMBER(10,0) AUTOINCREMENT PRIMARY KEY,
    POSITION_TITLE VARCHAR(100) NOT NULL,
    POSITION_CODE VARCHAR(20) NOT NULL UNIQUE,
    DEPARTMENT_ID NUMBER(10,0) NOT NULL,
    JOB_LEVEL NUMBER(2,0),
    MIN_SALARY DECIMAL(12,2),
    MAX_SALARY DECIMAL(12,2),
    DESCRIPTION TEXT,
    REQUIREMENTS TEXT,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);

-- Employees Table
CREATE TABLE IF NOT EXISTS EMPLOYEES (
    EMPLOYEE_ID NUMBER(10,0) AUTOINCREMENT PRIMARY KEY,
    EMPLOYEE_NUMBER VARCHAR(20) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    MIDDLE_NAME VARCHAR(50),
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PHONE VARCHAR(20),
    MOBILE VARCHAR(20),
    BIRTH_DATE DATE,
    GENDER VARCHAR(10),
    MARITAL_STATUS VARCHAR(20),
    ADDRESS VARCHAR(200),
    CITY VARCHAR(50),
    STATE_PROVINCE VARCHAR(50),
    POSTAL_CODE VARCHAR(20),
    COUNTRY VARCHAR(30),
    HIRE_DATE DATE NOT NULL,
    TERMINATION_DATE DATE,
    POSITION_ID NUMBER(10,0) NOT NULL,
    DEPARTMENT_ID NUMBER(10,0) NOT NULL,
    MANAGER_ID NUMBER(10,0),
    EMPLOYMENT_TYPE VARCHAR(20) DEFAULT 'FULL_TIME',
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    EMERGENCY_CONTACT_NAME VARCHAR(100),
    EMERGENCY_CONTACT_PHONE VARCHAR(20),
    EMERGENCY_CONTACT_RELATIONSHIP VARCHAR(50),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (POSITION_ID) REFERENCES POSITIONS(POSITION_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

-- Payroll Table
CREATE TABLE IF NOT EXISTS PAYROLL (
    PAYROLL_ID NUMBER(10,0) AUTOINCREMENT PRIMARY KEY,
    EMPLOYEE_ID NUMBER(10,0) NOT NULL,
    PAY_PERIOD_START DATE NOT NULL,
    PAY_PERIOD_END DATE NOT NULL,
    PAY_DATE DATE NOT NULL,
    BASE_SALARY DECIMAL(12,2) NOT NULL,
    OVERTIME_HOURS DECIMAL(5,2) DEFAULT 0.00,
    OVERTIME_RATE DECIMAL(8,2) DEFAULT 0.00,
    OVERTIME_PAY DECIMAL(12,2) DEFAULT 0.00,
    BONUS DECIMAL(12,2) DEFAULT 0.00,
    COMMISSION DECIMAL(12,2) DEFAULT 0.00,
    GROSS_PAY DECIMAL(12,2) NOT NULL,
    FEDERAL_TAX DECIMAL(12,2) DEFAULT 0.00,
    STATE_TAX DECIMAL(12,2) DEFAULT 0.00,
    SOCIAL_SECURITY DECIMAL(12,2) DEFAULT 0.00,
    MEDICARE DECIMAL(12,2) DEFAULT 0.00,
    HEALTH_INSURANCE DECIMAL(12,2) DEFAULT 0.00,
    RETIREMENT_401K DECIMAL(12,2) DEFAULT 0.00,
    OTHER_DEDUCTIONS DECIMAL(12,2) DEFAULT 0.00,
    TOTAL_DEDUCTIONS DECIMAL(12,2) DEFAULT 0.00,
    NET_PAY DECIMAL(12,2) NOT NULL,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

-- Employee Performance Table
CREATE TABLE IF NOT EXISTS EMPLOYEE_PERFORMANCE (
    PERFORMANCE_ID NUMBER(10,0) AUTOINCREMENT PRIMARY KEY,
    EMPLOYEE_ID NUMBER(10,0) NOT NULL,
    REVIEW_PERIOD_START DATE NOT NULL,
    REVIEW_PERIOD_END DATE NOT NULL,
    REVIEWER_ID NUMBER(10,0) NOT NULL,
    PERFORMANCE_SCORE DECIMAL(3,2),
    GOALS_MET NUMBER(2,0),
    TOTAL_GOALS NUMBER(2,0),
    STRENGTHS TEXT,
    AREAS_FOR_IMPROVEMENT TEXT,
    DEVELOPMENT_PLAN TEXT,
    SALARY_INCREASE_PERCENT DECIMAL(5,2),
    PROMOTION_ELIGIBLE BOOLEAN DEFAULT FALSE,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    FOREIGN KEY (REVIEWER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

-- Update department manager foreign key after employees table exists
ALTER TABLE DEPARTMENTS ADD CONSTRAINT FK_DEPT_MANAGER 
FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);

-- Note: Snowflake uses automatic clustering and micro-partitions for optimization
-- No explicit indexes needed for regular tables