-- =====================================================
-- Products Schema Tables
-- Description: Tables for product catalog and inventory
-- Version: 1.0
-- Date: 2025-07-19
-- =====================================================

USE SCHEMA RETAILWORKS_DB.PRODUCTS_SCHEMA;

-- Categories Table
CREATE TABLE IF NOT EXISTS CATEGORIES (
    CATEGORY_ID NUMBER(10,0) AUTOINCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPTION TEXT,
    PARENT_CATEGORY_ID NUMBER(10,0),
    IMAGE_URL VARCHAR(200),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
);

-- Suppliers Table
CREATE TABLE IF NOT EXISTS SUPPLIERS (
    SUPPLIER_ID NUMBER(10,0) AUTOINCREMENT PRIMARY KEY,
    SUPPLIER_NAME VARCHAR(100) NOT NULL,
    CONTACT_NAME VARCHAR(100),
    CONTACT_TITLE VARCHAR(50),
    ADDRESS VARCHAR(200),
    CITY VARCHAR(50),
    REGION VARCHAR(50),
    POSTAL_CODE VARCHAR(20),
    COUNTRY VARCHAR(30),
    PHONE VARCHAR(20),
    FAX VARCHAR(20),
    EMAIL VARCHAR(100),
    WEBSITE VARCHAR(200),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    RATING NUMBER(2,1) DEFAULT 5.0,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Products Table
CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID NUMBER(10,0) AUTOINCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    PRODUCT_NUMBER VARCHAR(25) NOT NULL UNIQUE,
    CATEGORY_ID NUMBER(10,0) NOT NULL,
    SUPPLIER_ID NUMBER(10,0),
    DESCRIPTION TEXT,
    COLOR VARCHAR(15),
    SIZE VARCHAR(10),
    WEIGHT DECIMAL(8,2),
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    COST DECIMAL(10,2),
    LIST_PRICE DECIMAL(10,2),
    DISCONTINUED BOOLEAN DEFAULT FALSE,
    REORDER_LEVEL NUMBER(10,0) DEFAULT 10,
    UNITS_IN_STOCK NUMBER(10,0) DEFAULT 0,
    UNITS_ON_ORDER NUMBER(10,0) DEFAULT 0,
    IMAGE_URL VARCHAR(200),
    PRODUCT_LINE VARCHAR(20),
    CLASS VARCHAR(10),
    STYLE VARCHAR(10),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID)
);

-- Inventory Table
CREATE TABLE IF NOT EXISTS INVENTORY (
    INVENTORY_ID NUMBER(10,0) AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID NUMBER(10,0) NOT NULL,
    LOCATION_CODE VARCHAR(10) NOT NULL,
    QUANTITY_ON_HAND NUMBER(10,0) NOT NULL DEFAULT 0,
    QUANTITY_AVAILABLE NUMBER(10,0) NOT NULL DEFAULT 0,
    QUANTITY_ALLOCATED NUMBER(10,0) NOT NULL DEFAULT 0,
    REORDER_POINT NUMBER(10,0) DEFAULT 10,
    MAX_STOCK_LEVEL NUMBER(10,0) DEFAULT 100,
    LAST_COUNT_DATE DATE,
    LAST_RECEIVED_DATE DATE,
    AVERAGE_COST DECIMAL(10,2),
    LAST_COST DECIMAL(10,2),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    UNIQUE(PRODUCT_ID, LOCATION_CODE)
);

-- Note: Snowflake uses automatic clustering and micro-partitions for optimization
-- No explicit indexes needed for regular tables