-- =====================================================
-- Sales Schema Tables
-- Description: Tables for sales operations
-- Version: 1.0
-- Date: 2025-07-19
-- =====================================================

USE SCHEMA RETAILWORKS_DB.SALES_SCHEMA;

-- Sales Territories Table
CREATE TABLE IF NOT EXISTS SALES_TERRITORIES (
    TERRITORY_ID NUMBER(10,0) AUTOINCREMENT PRIMARY KEY,
    TERRITORY_NAME VARCHAR(50) NOT NULL,
    TERRITORY_CODE VARCHAR(10) NOT NULL UNIQUE,
    REGION VARCHAR(30) NOT NULL,
    COUNTRY VARCHAR(30) NOT NULL,
    MANAGER_ID NUMBER(10,0),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Sales Representatives Table
CREATE TABLE IF NOT EXISTS SALES_REPS (
    SALES_REP_ID NUMBER(10,0) AUTOINCREMENT PRIMARY KEY,
    EMPLOYEE_ID NUMBER(10,0) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PHONE VARCHAR(20),
    TERRITORY_ID NUMBER(10,0),
    HIRE_DATE DATE NOT NULL,
    COMMISSION_RATE DECIMAL(5,4) DEFAULT 0.05,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (TERRITORY_ID) REFERENCES SALES_TERRITORIES(TERRITORY_ID)
);

-- Orders Table
CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID NUMBER(10,0) AUTOINCREMENT PRIMARY KEY,
    ORDER_NUMBER VARCHAR(20) NOT NULL UNIQUE,
    CUSTOMER_ID NUMBER(10,0) NOT NULL,
    SALES_REP_ID NUMBER(10,0),
    ORDER_DATE DATE NOT NULL,
    REQUIRED_DATE DATE,
    SHIPPED_DATE DATE,
    SHIP_VIA VARCHAR(50),
    FREIGHT DECIMAL(10,2) DEFAULT 0.00,
    SHIP_NAME VARCHAR(100),
    SHIP_ADDRESS VARCHAR(200),
    SHIP_CITY VARCHAR(50),
    SHIP_REGION VARCHAR(50),
    SHIP_POSTAL_CODE VARCHAR(20),
    SHIP_COUNTRY VARCHAR(30),
    SUBTOTAL DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    TAX_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    TOTAL_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (SALES_REP_ID) REFERENCES SALES_REPS(SALES_REP_ID)
);

-- Order Items Table
CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
    ORDER_ITEM_ID NUMBER(10,0) AUTOINCREMENT PRIMARY KEY,
    ORDER_ID NUMBER(10,0) NOT NULL,
    PRODUCT_ID NUMBER(10,0) NOT NULL,
    QUANTITY NUMBER(10,0) NOT NULL,
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    DISCOUNT DECIMAL(5,4) DEFAULT 0.00,
    LINE_TOTAL DECIMAL(12,2),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

-- Note: Snowflake uses automatic clustering and micro-partitions for optimization
-- No explicit indexes needed for regular tables