-- =====================================================
-- Staging Schema Tables
-- Description: Staging tables for ETL processes
-- Version: 1.0
-- Date: 2025-07-19
-- =====================================================

USE SCHEMA {{ database_name | default('RETAILWORKS_DB') }}.STAGING_SCHEMA{{ schema_suffix | default('') }};

-- File Format for CSV imports
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
NULL_IF = ('NULL', 'null', '')
EMPTY_FIELD_AS_NULL = TRUE
COMPRESSION = AUTO;

-- File Format for JSON imports
CREATE OR REPLACE FILE FORMAT JSON_FORMAT
TYPE = 'JSON'
COMPRESSION = AUTO;

-- Stage for external data files
CREATE OR REPLACE STAGE EXTERNAL_STAGE
FILE_FORMAT = CSV_FORMAT
COMMENT = 'Stage for external data file imports';

-- Raw Customers Staging Table
CREATE OR REPLACE TABLE STG_CUSTOMERS_RAW (
    CUSTOMER_NUMBER VARCHAR(20),
    CUSTOMER_TYPE VARCHAR(20),
    COMPANY_NAME VARCHAR(100),
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    BIRTH_DATE VARCHAR(20),
    GENDER VARCHAR(10),
    ANNUAL_INCOME VARCHAR(20),
    ADDRESS_LINE_1 VARCHAR(200),
    ADDRESS_LINE_2 VARCHAR(200),
    CITY VARCHAR(50),
    STATE_PROVINCE VARCHAR(50),
    POSTAL_CODE VARCHAR(20),
    COUNTRY VARCHAR(30),
    REGISTRATION_DATE VARCHAR(20),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME VARCHAR(200),
    ROW_NUMBER NUMBER
);

-- Raw Products Staging Table
CREATE OR REPLACE TABLE STG_PRODUCTS_RAW (
    PRODUCT_NUMBER VARCHAR(25),
    PRODUCT_NAME VARCHAR(100),
    CATEGORY_NAME VARCHAR(50),
    SUPPLIER_NAME VARCHAR(100),
    DESCRIPTION TEXT,
    COLOR VARCHAR(15),
    SIZE VARCHAR(10),
    WEIGHT VARCHAR(20),
    UNIT_PRICE VARCHAR(20),
    COST VARCHAR(20),
    LIST_PRICE VARCHAR(20),
    DISCONTINUED VARCHAR(10),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME VARCHAR(200),
    ROW_NUMBER NUMBER
);

-- Raw Orders Staging Table
CREATE OR REPLACE TABLE STG_ORDERS_RAW (
    ORDER_NUMBER VARCHAR(20),
    CUSTOMER_NUMBER VARCHAR(20),
    SALES_REP_EMAIL VARCHAR(100),
    ORDER_DATE VARCHAR(20),
    REQUIRED_DATE VARCHAR(20),
    SHIPPED_DATE VARCHAR(20),
    SHIP_VIA VARCHAR(50),
    FREIGHT VARCHAR(20),
    SHIP_NAME VARCHAR(100),
    SHIP_ADDRESS VARCHAR(200),
    SHIP_CITY VARCHAR(50),
    SHIP_COUNTRY VARCHAR(30),
    STATUS VARCHAR(20),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME VARCHAR(200),
    ROW_NUMBER NUMBER
);

-- Raw Order Items Staging Table
CREATE OR REPLACE TABLE STG_ORDER_ITEMS_RAW (
    ORDER_NUMBER VARCHAR(20),
    PRODUCT_NUMBER VARCHAR(25),
    QUANTITY VARCHAR(20),
    UNIT_PRICE VARCHAR(20),
    DISCOUNT VARCHAR(20),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME VARCHAR(200),
    ROW_NUMBER NUMBER
);

-- Data Quality Issues Tracking Table
CREATE OR REPLACE TABLE DATA_QUALITY_ISSUES (
    ISSUE_ID NUMBER(15,0) AUTOINCREMENT PRIMARY KEY,
    TABLE_NAME VARCHAR(100) NOT NULL,
    COLUMN_NAME VARCHAR(100),
    ISSUE_TYPE VARCHAR(50) NOT NULL,
    ISSUE_DESCRIPTION TEXT NOT NULL,
    RECORD_IDENTIFIER VARCHAR(200),
    RAW_VALUE TEXT,
    SUGGESTED_VALUE TEXT,
    SEVERITY VARCHAR(20) DEFAULT 'MEDIUM',
    STATUS VARCHAR(20) DEFAULT 'OPEN',
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RESOLVED_DATE TIMESTAMP_NTZ,
    RESOLVED_BY VARCHAR(100)
);

-- ETL Process Log Table
CREATE OR REPLACE TABLE ETL_PROCESS_LOG (
    LOG_ID NUMBER(15,0) AUTOINCREMENT PRIMARY KEY,
    PROCESS_NAME VARCHAR(100) NOT NULL,
    START_TIME TIMESTAMP_NTZ NOT NULL,
    END_TIME TIMESTAMP_NTZ,
    STATUS VARCHAR(20) NOT NULL,
    RECORDS_PROCESSED NUMBER(15,0),
    RECORDS_INSERTED NUMBER(15,0),
    RECORDS_UPDATED NUMBER(15,0),
    RECORDS_REJECTED NUMBER(15,0),
    ERROR_MESSAGE TEXT,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Data Lineage Tracking Table
CREATE OR REPLACE TABLE DATA_LINEAGE (
    LINEAGE_ID NUMBER(15,0) AUTOINCREMENT PRIMARY KEY,
    SOURCE_TABLE VARCHAR(100) NOT NULL,
    SOURCE_COLUMN VARCHAR(100),
    TARGET_TABLE VARCHAR(100) NOT NULL,
    TARGET_COLUMN VARCHAR(100),
    TRANSFORMATION_RULE TEXT,
    PROCESS_NAME VARCHAR(100),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Cleansed staging tables for validated data
CREATE OR REPLACE TABLE STG_CUSTOMERS_CLEAN (
    CUSTOMER_NUMBER VARCHAR(20),
    CUSTOMER_TYPE VARCHAR(20),
    COMPANY_NAME VARCHAR(100),
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    BIRTH_DATE DATE,
    GENDER VARCHAR(10),
    ANNUAL_INCOME DECIMAL(15,2),
    ADDRESS_LINE_1 VARCHAR(200),
    ADDRESS_LINE_2 VARCHAR(200),
    CITY VARCHAR(50),
    STATE_PROVINCE VARCHAR(50),
    POSTAL_CODE VARCHAR(20),
    COUNTRY VARCHAR(30),
    REGISTRATION_DATE DATE,
    PROCESSED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE VARCHAR(200),
    VALIDATION_STATUS VARCHAR(20) DEFAULT 'VALID'
);

CREATE OR REPLACE TABLE STG_PRODUCTS_CLEAN (
    PRODUCT_NUMBER VARCHAR(25),
    PRODUCT_NAME VARCHAR(100),
    CATEGORY_NAME VARCHAR(50),
    SUPPLIER_NAME VARCHAR(100),
    DESCRIPTION TEXT,
    COLOR VARCHAR(15),
    SIZE VARCHAR(10),
    WEIGHT DECIMAL(8,2),
    UNIT_PRICE DECIMAL(10,2),
    COST DECIMAL(10,2),
    LIST_PRICE DECIMAL(10,2),
    DISCONTINUED BOOLEAN,
    PROCESSED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE VARCHAR(200),
    VALIDATION_STATUS VARCHAR(20) DEFAULT 'VALID'
);

-- Create indexes for staging tables
CREATE INDEX IDX_STG_CUSTOMERS_RAW_LOAD_TIME ON STG_CUSTOMERS_RAW(LOAD_TIMESTAMP);
CREATE INDEX IDX_STG_PRODUCTS_RAW_LOAD_TIME ON STG_PRODUCTS_RAW(LOAD_TIMESTAMP);
CREATE INDEX IDX_STG_ORDERS_RAW_LOAD_TIME ON STG_ORDERS_RAW(LOAD_TIMESTAMP);
CREATE INDEX IDX_ETL_LOG_PROCESS_NAME ON ETL_PROCESS_LOG(PROCESS_NAME);
CREATE INDEX IDX_ETL_LOG_START_TIME ON ETL_PROCESS_LOG(START_TIME);
CREATE INDEX IDX_DQ_ISSUES_TABLE_NAME ON DATA_QUALITY_ISSUES(TABLE_NAME);
CREATE INDEX IDX_DQ_ISSUES_STATUS ON DATA_QUALITY_ISSUES(STATUS);