-- =====================================================
-- Create Staging Tables for CSV Data Loading
-- Description: Creates staging tables for the generated sample data
-- =====================================================

USE DATABASE RETAILWORKS_DB;
CREATE SCHEMA IF NOT EXISTS STAGING_SCHEMA_DEV;
USE SCHEMA STAGING_SCHEMA_DEV;

-- File Format for CSV imports
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
NULL_IF = ('NULL', 'null', '')
EMPTY_FIELD_AS_NULL = TRUE
COMPRESSION = AUTO;

-- Staging table for customer segments CSV
CREATE TABLE IF NOT EXISTS STG_CUSTOMER_SEGMENTS_RAW (
    SEGMENT_ID VARCHAR(10),
    SEGMENT_NAME VARCHAR(50),
    DESCRIPTION VARCHAR(200),
    MIN_ANNUAL_REVENUE VARCHAR(20),
    MAX_ANNUAL_REVENUE VARCHAR(20),
    DISCOUNT_RATE VARCHAR(10),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME VARCHAR(200),
    ROW_NUMBER NUMBER
);

-- Staging table for categories CSV
CREATE TABLE IF NOT EXISTS STG_CATEGORIES_RAW (
    CATEGORY_ID VARCHAR(10),
    CATEGORY_NAME VARCHAR(50),
    DESCRIPTION VARCHAR(200),
    PARENT_CATEGORY_ID VARCHAR(10),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME VARCHAR(200),
    ROW_NUMBER NUMBER
);

-- Staging table for suppliers CSV
CREATE TABLE IF NOT EXISTS STG_SUPPLIERS_RAW (
    SUPPLIER_ID VARCHAR(10),
    SUPPLIER_NAME VARCHAR(100),
    CONTACT_NAME VARCHAR(100),
    CONTACT_TITLE VARCHAR(50),
    ADDRESS VARCHAR(200),
    CITY VARCHAR(50),
    REGION VARCHAR(50),
    POSTAL_CODE VARCHAR(20),
    COUNTRY VARCHAR(30),
    PHONE VARCHAR(20),
    EMAIL VARCHAR(100),
    WEBSITE VARCHAR(200),
    STATUS VARCHAR(20),
    RATING VARCHAR(10),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME VARCHAR(200),
    ROW_NUMBER NUMBER
);

-- Staging table for addresses CSV
CREATE TABLE IF NOT EXISTS STG_ADDRESSES_RAW (
    ADDRESS_ID VARCHAR(10),
    CUSTOMER_ID VARCHAR(10),
    ADDRESS_TYPE VARCHAR(20),
    ADDRESS_LINE_1 VARCHAR(200),
    ADDRESS_LINE_2 VARCHAR(200),
    CITY VARCHAR(50),
    STATE_PROVINCE VARCHAR(50),
    POSTAL_CODE VARCHAR(20),
    COUNTRY VARCHAR(30),
    IS_DEFAULT VARCHAR(10),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME VARCHAR(200),
    ROW_NUMBER NUMBER
);

-- Staging table for customers CSV
CREATE TABLE IF NOT EXISTS STG_CUSTOMERS_RAW (
    CUSTOMER_NUMBER VARCHAR(20),
    CUSTOMER_TYPE VARCHAR(20),
    COMPANY_NAME VARCHAR(100),
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    BIRTH_DATE VARCHAR(20),
    GENDER VARCHAR(10),
    ANNUAL_INCOME VARCHAR(20),
    STATUS VARCHAR(20),
    PREFERRED_LANGUAGE VARCHAR(10),
    MARKETING_OPT_IN VARCHAR(10),
    REGISTRATION_DATE VARCHAR(20),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME VARCHAR(200),
    ROW_NUMBER NUMBER
);

-- Staging table for products CSV
CREATE TABLE IF NOT EXISTS STG_PRODUCTS_RAW (
    PRODUCT_NUMBER VARCHAR(25),
    PRODUCT_NAME VARCHAR(100),
    CATEGORY_NAME VARCHAR(50),
    SUPPLIER_NAME VARCHAR(100),
    DESCRIPTION TEXT,
    COLOR VARCHAR(15),
    SIZE VARCHAR(10),
    WEIGHT VARCHAR(20),
    UNIT_PRICE VARCHAR(20),
    COST VARCHAR(20),
    LIST_PRICE VARCHAR(20),
    DISCONTINUED VARCHAR(10),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME VARCHAR(200),
    ROW_NUMBER NUMBER
);

-- Staging table for departments CSV
CREATE TABLE IF NOT EXISTS STG_DEPARTMENTS_RAW (
    DEPARTMENT_ID VARCHAR(10),
    DEPARTMENT_NAME VARCHAR(100),
    DEPARTMENT_CODE VARCHAR(20),
    DESCRIPTION VARCHAR(200),
    BUDGET VARCHAR(20),
    LOCATION VARCHAR(100),
    PHONE VARCHAR(20),
    EMAIL VARCHAR(100),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME VARCHAR(200),
    ROW_NUMBER NUMBER
);

-- Staging table for positions CSV
CREATE TABLE IF NOT EXISTS STG_POSITIONS_RAW (
    POSITION_ID VARCHAR(10),
    POSITION_TITLE VARCHAR(100),
    POSITION_CODE VARCHAR(20),
    DEPARTMENT_ID VARCHAR(10),
    JOB_LEVEL VARCHAR(10),
    MIN_SALARY VARCHAR(20),
    MAX_SALARY VARCHAR(20),
    DESCRIPTION VARCHAR(200),
    STATUS VARCHAR(20),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME VARCHAR(200),
    ROW_NUMBER NUMBER
);

-- Clean staging tables
CREATE TABLE IF NOT EXISTS STG_CUSTOMER_SEGMENTS_CLEAN (
    SEGMENT_ID NUMBER,
    SEGMENT_NAME VARCHAR(50),
    DESCRIPTION VARCHAR(200),
    MIN_ANNUAL_REVENUE DECIMAL(15,2),
    MAX_ANNUAL_REVENUE DECIMAL(15,2),
    DISCOUNT_RATE DECIMAL(5,4),
    PROCESSED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE VARCHAR(200),
    VALIDATION_STATUS VARCHAR(20) DEFAULT 'VALID'
);

CREATE TABLE IF NOT EXISTS STG_CATEGORIES_CLEAN (
    CATEGORY_ID NUMBER,
    CATEGORY_NAME VARCHAR(50),
    DESCRIPTION VARCHAR(200),
    PARENT_CATEGORY_ID NUMBER,
    PROCESSED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE VARCHAR(200),
    VALIDATION_STATUS VARCHAR(20) DEFAULT 'VALID'
);

CREATE TABLE IF NOT EXISTS STG_SUPPLIERS_CLEAN (
    SUPPLIER_ID NUMBER,
    SUPPLIER_NAME VARCHAR(100),
    CONTACT_NAME VARCHAR(100),
    CONTACT_TITLE VARCHAR(50),
    ADDRESS VARCHAR(200),
    CITY VARCHAR(50),
    REGION VARCHAR(50),
    POSTAL_CODE VARCHAR(20),
    COUNTRY VARCHAR(30),
    PHONE VARCHAR(20),
    EMAIL VARCHAR(100),
    WEBSITE VARCHAR(200),
    STATUS VARCHAR(20),
    RATING DECIMAL(3,1),
    PROCESSED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE VARCHAR(200),
    VALIDATION_STATUS VARCHAR(20) DEFAULT 'VALID'
);

SELECT 'Staging tables created successfully!' as MESSAGE;